#ifndef PACKETS_H
#define PACKETS_H

#define PACKET_NO_WRITE return QByteArray();
#define PACKET_NO_READ Q_UNUSED(data);

enum Packets
{
	AUTH_PACKET = 100,
	AUTH_REJECT_PACKET = 101,
	AUTH_ACCEPT_PACKET = 102,
	REGISTER_PACKET = 103,
	INIT_LOCATION_PACKET = 301,
	INIT_PROFILE_PACKET = 500,
	UPDATE_PROFILE_PACKET = 501,
	CHECK_AVATAR_HASH_PACKET = 1000,
	UPDATE_AVATAR_PACKET = 1001,
	INIT_CHATS_PACKET = 1002,
	GET_INIT_MESSAGES_PACKET = 1003,
	INIT_MESSAGES_PACKET = 1004,
	SEND_MESSAGE_PACKET = 2000,
	NEW_MESSAGE_PACKET = 2001
};

#endif // PACKETS_H
