#ifndef PACKETS_H
#define PACKETS_H

enum Packets
{
	AUTH_PACKET = 100,
	AUTH_REJECT_PACKET = 101,
	AUTH_ACCEPT_PACKET = 102,
	REGISTER_PACKET = 103,
	INIT_LOCATION_PACKET = 301,
	INIT_PROFILE_PACKET = 500,
	UPDATE_PROFILE_PACKET = 501,
	CHECK_AVATAR_HASH_PACKET = 1000,
	UPDATE_AVATAR_PACKET = 1001,
};

#endif // PACKETS_H
